services:
  drupal:
    image: drupal:10-apache
    container_name: drupal
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DRUPAL_DB_HOST=aws-drupal.cg5uoue2wj9p.us-east-1.rds.amazonaws.com
      - DRUPAL_DB_PORT=3306
      - DRUPAL_DB_NAME=drupal
      - DRUPAL_DB_USER=admin
      - DRUPAL_DB_PASSWORD=0elfrkGoxf7PFRxmlCBZ
